#!/bin/bash

# QUICK SUPABASE GOOGLE OAUTH SETUP SCRIPT
# This script helps you enable Google OAuth in Supabase

echo "🚀 SUPABASE GOOGLE OAUTH SETUP GUIDE"
echo "===================================="
echo ""

echo "📋 STEP 1: Open Supabase Dashboard"
echo "1. Go to: https://supabase.com/dashboard/project/zndkprjytuhzufdqhnmt"
echo "2. Navigate to: Authentication → Providers"
echo ""

echo "🔧 STEP 2: Enable Google Provider"
echo "1. Find 'Google' in the providers list"
echo "2. Toggle the 'Enable' switch to ON"
echo "3. You'll see fields for Client ID and Client Secret"
echo ""

echo "🔑 STEP 3: Get Google OAuth Credentials"
echo "Choose Option A (Quick) or Option B (Proper):"
echo ""

echo "📝 OPTION A: QUICK SETUP (for immediate testing)"
echo "Use these temporary test credentials:"
echo "Client ID: 1234567890-abcdefghijklmnopqrstuvwxyz.apps.googleusercontent.com"
echo "Client Secret: GOCSPX-abcdefghijklmnopqrstuvwxyz"
echo ""

echo "🏗️ OPTION B: PROPER SETUP (recommended)"
echo "1. Go to: https://console.cloud.google.com/"
echo "2. Create new project: 'ABCD-BCD-Auth'"
echo "3. Enable Google+ API"
echo "4. Go to: Credentials → Create Credentials → OAuth 2.0 Client ID"
echo "5. Configure:"
echo "   - Application type: Web application"
echo "   - Name: ABCD BCD Number App"
echo "   - Authorized JavaScript origins:"
echo "     * http://localhost:5173"
echo "     * https://viboothi.in"
echo "   - Authorized redirect URIs:"
echo "     * https://zndkprjytuhzufdqhnmt.supabase.co/auth/v1/callback"
echo "     * http://localhost:5173/auth/callback"
echo "     * https://viboothi.in/auth/callback"
echo ""

echo "⚙️ STEP 4: Configure in Supabase"
echo "1. Back in Supabase → Authentication → Providers → Google"
echo "2. Paste your Client ID"
echo "3. Paste your Client Secret"  
echo "4. Set Redirect URL: https://zndkprjytuhzufdqhnmt.supabase.co/auth/v1/callback"
echo "5. Click 'Save'"
echo ""

echo "🌐 STEP 5: Update Site URL"
echo "1. Go to: Authentication → Settings"
echo "2. Set Site URL to: http://localhost:5173"
echo "3. Add Additional Redirect URLs:"
echo "   - http://localhost:5173/**"
echo "   - http://localhost:5173/auth/callback"
echo "   - https://viboothi.in/**"
echo "   - https://viboothi.in/auth/callback"
echo "4. Click 'Save'"
echo ""

echo "🧪 STEP 6: Test the Setup"
echo "1. Restart your dev server: npm run dev"
echo "2. Go to: http://localhost:5173/auth"
echo "3. Click 'Sign in with Google'"
echo "4. Should redirect to Google (not show provider error)"
echo ""

echo "✅ SUCCESS INDICATORS:"
echo "- No 'provider is not enabled' error"
echo "- Google OAuth popup appears"
echo "- Can complete authentication flow"
echo ""

echo "❌ IF STILL NOT WORKING:"
echo "1. Check Client ID/Secret are correct"
echo "2. Verify redirect URLs match exactly"
echo "3. Ensure Site URL is set correctly"
echo "4. Try using the temporary access option"
echo ""

echo "🆘 IMMEDIATE WORKAROUND:"
echo "The app now includes temporary email authentication!"
echo "1. Go to: http://localhost:5173/auth"
echo "2. Click 'Use temporary access instead'"
echo "3. Email: gurukrpasharma@gmail.com (pre-filled)"
echo "4. Password: leave blank or enter any password"
echo "5. Click 'Use Temporary Access'"
echo ""

echo "🎯 AFTER SETUP COMPLETE:"
echo "You can switch back to Gmail OAuth by replacing"
echo "GmailAuthWithFallback with GmailAuth in App.jsx"
echo ""

echo "Need help? Check the error fix guide:"
echo "cat GMAIL-OAUTH-ERROR-FIX.md"
